### ISSUE TITLE
Mismatch between intro and body

### ISSUE THREAD

**Issue by krmaffey** [mlte-team/mlte-framework#23]
From reviewer 2

"Study Goal: The paper focused on the challenges related to ML systems testing in the introduction section. However, the rest of the study discusses the challenges related to defining, communicating, and fulfilling the requirements, which confuses the readers about the study's main goal. I suggest the authors revisit the introduction section and align it with the rest of the paper (i.e., ML requirement engineering challenges). On the other hand, the proposed framework could help organizations govern ML systems development, which is another useful application of MLTE that might be worth investigation."

**Comment by krmaffey** [comment]
@JennyNiemann can we chat about this one? I am not totally confident of how to approach it - I don't think it is unfounded but I also don't know exactly how we should change things for it

**Comment by JennyNiemann** [comment]
possible options:
- reword the introduction to say "failing to meet the goals of the system" instead of just testing. we wrote MTLE as a tool to help facilitate / ensure requirements and systems goals are achieved so saying just "testing" might confuse the concepts?
- make it more clear we are talking about requirement negotiation specific to ML system eval? or figure out how to express why focusing on requirements is essential for evaluation
- make it more clear MLTE is more that just defining, communicating, and fulfilling the requirements. I feel like we do but...
- make it more clear why we focus so much on "requirement engineering challenges" to motivate MTLE
